package com.unbank.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Aug 11 14:15:52 GMT+08:00 2014
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://cxfinterface.unbank.com/", name = "Autoclassinterface")
@XmlSeeAlso({ObjectFactory.class})
public interface Autoclassinterface {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "comparesimilarity", targetNamespace = "http://cxfinterface.unbank.com/", className = "com.unbank.wsdl.Comparesimilarity")
    @ResponseWrapper(localName = "comparesimilarityResponse", targetNamespace = "http://cxfinterface.unbank.com/", className = "com.unbank.wsdl.ComparesimilarityResponse")
    @WebMethod
    public java.lang.String comparesimilarity(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
