
/*
 * 
 */

package com.unbank.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Aug 11 14:15:52 GMT+08:00 2014
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "AutoclassinterfaceImplService", 
                  wsdlLocation = "http://127.0.0.1:8080/automaticsort/Autoclassinterface?wsdl",
                  targetNamespace = "http://cxfinterface.unbank.com/") 
public class AutoclassinterfaceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://cxfinterface.unbank.com/", "AutoclassinterfaceImplService");
    public final static QName AutoclassinterfaceImplPort = new QName("http://cxfinterface.unbank.com/", "AutoclassinterfaceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/automaticsort/Autoclassinterface?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://127.0.0.1:8080/automaticsort/Autoclassinterface?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AutoclassinterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AutoclassinterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutoclassinterfaceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Autoclassinterface
     */
    @WebEndpoint(name = "AutoclassinterfaceImplPort")
    public Autoclassinterface getAutoclassinterfaceImplPort() {
        return super.getPort(AutoclassinterfaceImplPort, Autoclassinterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Autoclassinterface
     */
    @WebEndpoint(name = "AutoclassinterfaceImplPort")
    public Autoclassinterface getAutoclassinterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(AutoclassinterfaceImplPort, Autoclassinterface.class, features);
    }

}
